import { AdmSolicitudDetalle } from "./IAdmSolicitudDetalle";

export interface AdmSolicitud {
    nAdmSolCodigo?: number;
    cPerCodigo?: string;
    cPerJuridica?: string;
    nAcdCampusCodigo?: number;
    cAcdCamDescCorta?: string;
    cAdmSolGrupo?: string;
    nAcdNivCodigo?: number;
    nAcdSubNivCodigo?: number;
    nAcdModCodigo?: number;
    cAcdModNombre?: string;
    nAcdProDefCodigo?: number;
    cAcdProNombre?: string;
    nPrdCodigo?: number;
    nPrdAdmCodigo?: number;
    cPrdAdmDescripcion?: string;
    nSedCodigo?: number;
    nPromCodigo?: number;
    nAdmSolModalidad?: number;
    nAdmSolSubModal?: number;
    nAdmSolTipo?: number;
    nAdmSolEstado?: number;
    dAdmSolFecVence?: Date;
    nInstitucionAcaCodigo?: number;
    nIntAcaLocalCodigo?: number;
    dPerFecGraduaIE?: Date;
    cCtaCteRecibo?: string;
    cAdmSolComentario?: string;
    nRegCodigo?: number;
    nUbiAdmCodigo?: number;
    dFechaEfectiva?: Date;
    nLstControlCodigo?: number;
    nEstM?: number;
    dFecRegistro?: Date;
    cPerUsuRegistro?: string;
    cHostRegistro?: string;
    cAdmSolUsuUpd?: string;
    dSolFechaUpdate?: Date;
    cSolHostUpd?: string;
    solDetEstDescripcion?: string;
    estado?: string;
    cEtapaSolicitud?: string;
    lAdmSolDetalle?: AdmSolicitudDetalle[];
}
