import { Campus } from "./ICampus";
import { GruposAcademicos } from "./IGruposAcademicos";
import { Nivel } from "./INivel";
import { Subnivel } from "./ISubnivel";

export class ProgramaEstudioDef {
    nAcdProDefCodigo?: number;
    nAcdProCodigo?: number;
    nAcdProDefTipConfig?: number;
    nAcdGruCodigo?: number;
    nAcdNivCodigo?: number;
    nAcdSubNivCodigo?: number;
    nAcdCampusCodigo?: number;
    bInterfazContable?: boolean;
    nConsCodigo?: number;
    nUniOrgCodigo?: number;
    nOpeCodigo?: number;
    nFilCodigo?: number;
    nSedCodigo?: number;
    nProyCodigo?: number;
    nSucCodigo?: number;
    nCtaRefPresupuesto?: number;
    nActCodigo?: number;
    nBieCodigo?: number;
    nAcdProDefEstado?: number;
    dAcdProDefFecha?: Date;
    cAcdProDefUsuario?: string;
    cAcdProDefHostRegistro?: string;
    dAcdProDefFechaUpd?: Date;
    cAcdProDefUsuarioUpd?: string;
    cAcdProDefHostUpd?: string;
    estado?: string;
    nAcdNivDes?: string;
    nAcdGruDes?: string;
    nAcdSubNivDes?: string;
    nAcdCampusdes?: string;
    nAcdProDes?: string;
    ProgramaYCampus?: string;
    cAcdGruDescripcion?: string;
    cAcdNivNombre?: string;
    cAcdSubNivNombre?: string;
    cAcdCamDescripcion?: string;
    cAcdProDescripcion?: string;
}
